In [1]:
print ("hello world")

hello world


In [4]:
z=5
y=5.0
b=1000
print("est-ce que Z est équivalent y?:",z==y)
print("est-ce que 'Parakou' est 'superieur' à Librevilles?:",'parakou' > 'Libreville')


est-ce que Z est équivalent y?: True
est-ce que 'Parakou' est 'superieur' à Librevilles?: True


Exercice d'application2

In [25]:
age=int(input("Quel est votre âge"))
if age >=18:
     print('vous piuvez voter')
     if age>=25:
           print('vous pouvez voter et aussi jouer au jeu de hasard')
else:
    print('patientez vous êtes encore trop jeune')

Quel est votre âge 25


vous piuvez voter
vous pouvez voter et aussi jouer au jeu de hasard


In [28]:
#boucle for avec range()
for i in range(1,6):
    print (i)

1
2
3
4
5


In [30]:
for i in range(6):
    print (i)

0
1
2
3
4
5


In [29]:
#changer le pas d'incrémentation
#boucle for avec range()
for i in range(1,6):
    print (i+2)
    

3
4
5
6
7


In [34]:
for i in 'python':
    print (i)

p
y
t
h
o
n


In [33]:
#changer le pas d'incrementation
for i in range(1,11,2):
    print (i)

1
3
5
7
9


In [36]:
#for imbriqué
for i in range(3):
    for i in 'bus':
        print (i)

b
u
s
b
u
s
b
u
s


In [38]:
#carré
for i in range(1,11):
    print(1,"au carré est égal à: ",i**2)

1 au carré est égal à:  1
1 au carré est égal à:  4
1 au carré est égal à:  9
1 au carré est égal à:  16
1 au carré est égal à:  25
1 au carré est égal à:  36
1 au carré est égal à:  49
1 au carré est égal à:  64
1 au carré est égal à:  81
1 au carré est égal à:  100


In [39]:
#affichage des 1à premiers naturels (0,1,2...9)
i=0 #initialisation de l'itératuer
while i<9:
    print(i)#instruction
    i=i+1#incrémenteur

0
1
2
3
4
5
6
7
8


In [40]:
#while avec break
i=1
while 1<=10:
    print(i)
    if i==6:
        break
    i=i+1

1
2
3
4
5
6


In [43]:
i=0
while i<=50:
    print(i)
    i=i+5
else:
  print(i,"nest pas inférieur à 50")

0
5
10
15
20
25
30
35
40
45
50
55 nest pas inférieur à 50


In [46]:
#ecrire un code qui determine si un nombre est pair ou impair
print("entre un nombre")
nombre=int(input())
if nombre % 2==0:
    print(nombre,'est un nombre pair')

else:
    print(nombre,'est un nombre imapir')

entre un nombre


 10


10 est un nombre pair


In [48]:
#Création d'une liste avec []
courses=['farine de blé','pâtes','lait','légumes']
courses

['farine de blé', 'pâtes', 'lait', 'légumes']

In [49]:
type(courses)


list

In [51]:
#retrouver un ou plusieurs éléments d'une liste grâce à l'indexation
courses[0]


'farine de blé'

In [52]:
courses[0:3]

['farine de blé', 'pâtes', 'lait']

In [54]:
#combiner les listes
l=courses+['viande','sucre']
l

['farine de blé', 'pâtes', 'lait', 'légumes', 'viande', 'sucre']

In [55]:
#on peut avoir une liste mixte
liste_mixte=[1,10.5,365,['Michale Jackson',1982,'Pop'],True,False]
liste_mixte

[1, 10.5, 365, ['Michale Jackson', 1982, 'Pop'], True, False]

In [56]:
type(liste_mixte)


list

In [57]:
#méthodes applicables aux listes
#.extend()
courses.extend(['chocolat','crèmes glacées','biscuit'])
courses

['farine de blé',
 'pâtes',
 'lait',
 'légumes',
 'chocolat',
 'crèmes glacées',
 'biscuit']

In [58]:
#position d'un élément dans une liste avec la méthode .index()
position_lait=courses.index('lait')
position_lait

2

In [61]:
#supprimer un élément d'une liste avec la méthode pop
courses.pop(2)

'lait'

In [62]:
courses

['farine de blé', 'pâtes', 'légumes', 'chocolat', 'crèmes glacées', 'biscuit']

In [69]:
#age moyen median minimum maximum de 5 éleves 
n=5 #effectif de la classe
age_list=[]
for i in range(5):
    print ('quel est votre âge')
    age=int(input())
    age_list.append(age)
age_list
    
    

quel est votre âge


 30


quel est votre âge


 22


quel est votre âge


 19


quel est votre âge


 25


quel est votre âge


 28


[30, 22, 19, 25, 28]

In [71]:
#importation de la librairie statistics
import statistics as st
#âge moyen
print('Age moyen:',round(st.mean(age_list)))
#age médian
print('Age médian',st.median(age_list))
#age maximum
print('Age maximum',max(age_list))
#age minimum
print('Age minium',min(age_list))

Age moyen: 25
Age médian 25
Age maximum 30
Age minium 19


Exercice d'application
Ajoutez 3 éléments de votre choix à la liste courses
appliquez la méthode.sort() à la liste courses
affichez la liste courses. Que constatez-vous?


In [72]:
courses=courses+['concombres','sardines','eau']
courses


['farine de blé',
 'pâtes',
 'légumes',
 'chocolat',
 'crèmes glacées',
 'biscuit',
 'concombres',
 'sardines',
 'eau']

In [75]:
courses.sort()
courses


['biscuit',
 'chocolat',
 'concombres',
 'crèmes glacées',
 'eau',
 'farine de blé',
 'légumes',
 'pâtes',
 'sardines']

In [2]:
#création d'un dctionnaire avec {}
acteur={'nom':'Jakie chnag','age':66,'pays':'Hong Kong'}
acteur

{'nom': 'Jakie chnag', 'age': 66, 'pays': 'Hong Kong'}

In [77]:
type(acteur)

dict

In [78]:
#valeur d'une clé
acteur['nom']


'Jakie chnag'

In [79]:
acteur.values

<function dict.values>

In [80]:
acteur.values()


dict_values(['Jakie chnag', 66, 'Hong Kong'])

In [81]:
acteur.keys()

dict_keys(['nom', 'age', 'pays'])

In [2]:
#changer la valeur d'une clé
acteur['age']=68
acteur

NameError: name 'acteur' is not defined

In [83]:
#ajout d'une paire clé-valeur dans un dictionnaire
acteur['films']=['le maître chinois','karate kids','police story']
acteur

{'nom': 'Jakie chnag',
 'age': 68,
 'pays': 'Hong Kong',
 'films': ['le maître chinois', 'karate kids', 'police story']}

In [1]:
acteur

NameError: name 'acteur' is not defined

In [3]:
#création d'un dctionnaire avec {}
acteur={'nom':'Jakie chnag','age':66,'pays':'Hong Kong'}
acteur


{'nom': 'Jakie chnag', 'age': 66, 'pays': 'Hong Kong'}

In [5]:
#valeur d'une clef
acteur['nom']

'Jakie chnag'

In [6]:
acteur.keys


<function dict.keys>

In [7]:
acteur.keys()


dict_keys(['nom', 'age', 'pays'])

In [8]:
acteur['age']=68


In [9]:
acteur

{'nom': 'Jakie chnag', 'age': 68, 'pays': 'Hong Kong'}

In [12]:
#ajout d'yne paire clef-valeur dans un dictionnaire
acteur['films']=['le maître chinois','karate kids','police story']
acteur

{'nom': 'Jakie chnag',
 'age': 68,
 'pays': 'Hong Kong',
 'films': ['le maître chinois', 'karate kids', 'police story']}

In [29]:
#liste de dictionnaires
acteurs=[
{'acteur':'Dwayne Johnson','revenu':89.4, 'films':['San Andreas','Iron']},
{'acteur':'Chris Hemsworth','revenu':76.4, 'films':['Vacation','kesari']},   
{'acteur':'Askay Kumari','revenu':65, 'films':['Karate kids','Police']} ,
{'acteur':'Ankra','revenu':100, 'films':['africa','Or']}
]
acteurs

[{'acteur': 'Dwayne Johnson',
  'revenu': 89.4,
  'films': ['San Andreas', 'Iron']},
 {'acteur': 'Chris Hemsworth',
  'revenu': 76.4,
  'films': ['Vacation', 'kesari']},
 {'acteur': 'Askay Kumari', 'revenu': 65, 'films': ['Karate kids', 'Police']},
 {'acteur': 'Ankra', 'revenu': 100, 'films': ['africa', 'Or']}]

Soit la liste de dictionnaires donnant des infos sur certains grands acteurs de Hllywood ci-dessous
Calculez le revenu moyen des acteurs (le revenu est en millions de dollars).
Affichez les infos des acteurs dont le salaire est supérieur au salaire moyen


In [31]:
liste_revenu_acteurs=[]
for acteur in acteurs:
    #print(acteur['revenu'])
    liste_revenu_acteurs.append(acteur['revenu'])
print( liste_revenu_acteurs)


    

[89.4, 76.4, 65, 100]


In [32]:
#revenu moyen
import statistics as st
print("revenu moyen ", round(st.mean(liste_revenu_acteurs),2))

revenu moyen  82.7


In [35]:
revenu_moyen=round(st.mean(liste_revenu_acteurs),2)
liste_acteurs_revenu_superieur_au_revmoyen=[]
for acteur in acteurs:
    if acteur['revenu']>revenu_moyen:
       #liste_acteurs_revenu_superieur_au_revmoyen.append(acteur['acteur'])
        print(acteur)
        

{'acteur': 'Dwayne Johnson', 'revenu': 89.4, 'films': ['San Andreas', 'Iron']}
{'acteur': 'Ankra', 'revenu': 100, 'films': ['africa', 'Or']}


In [6]:

#création d'un dictionnaire
notes={'Ryan':[18,16],'Elisa':[20,12],'Robert':[14,15],'Martine':[20,20]}
import pandas as pd
# transformation dictionnaire en dataframe
df=pd.DataFrame(notes)
df

Ryan  Elisa  Robert  Martine
0    18     20      14       20
1    16     12      15       20

In [13]:
#transposition de la dataframe df
df=df.T
df

0   1
Ryan     18  16
Elisa    20  12
Robert   14  15
Martine  20  20

In [15]:
#renommer colonnes
df.columns=['Maths','Français']
df

Maths  Français
Ryan        18        16
Elisa       20        12
Robert      14        15
Martine     20        20

In [16]:
#index de df
df.index
df

Maths  Français
Ryan        18        16
Elisa       20        12
Robert      14        15
Martine     20        20

In [7]:
df.index


RangeIndex(start=0, stop=2, step=1)

In [17]:
df

Maths  Français
Ryan        18        16
Elisa       20        12
Robert      14        15
Martine     20        20

ecrivez un programme qui attribue une remise aux clients d'une boutique en ligne en fonction de la valeur
de leur coupon de reduction. verifiez votre code en affichant le montant de la remise de chacun des clients de la liste. L'affichage
doit resembler à ceci
1 200 F20 20
2 150 P30 45.0
3 100 P50 50.0
4 110 F15 15




In [18]:
#liste des clients
clients=[
{'id':1,'total_panier':200,'coupon_code':'F20' },#F20remise fixe de 20
{'id':2,'total_panier':150,'coupon_code':'P30' },#P30 remise de 30%
{'id':3,'total_panier':100,'coupon_code':'P50' },#P50 remise fixe de 50%
{'id':4,'total_panier':110,'coupon_code':'F15' },#F15 remise fixe de 15    
]



In [19]:
clients

[{'id': 1, 'total_panier': 200, 'coupon_code': 'F20'},
 {'id': 2, 'total_panier': 150, 'coupon_code': 'P30'},
 {'id': 3, 'total_panier': 100, 'coupon_code': 'P50'},
 {'id': 4, 'total_panier': 110, 'coupon_code': 'F15'}]

In [39]:
#résolution
for client in clients:
    if client['coupon_code']=='F20':
        client['remise']=20
    elif client['coupon_code']=='P30':
        client['remise']=0.3*client['total_panier']
    elif client['coupon_code']=='P50':
        client['remise']=0.5*client['total_panier']
    else:
        client['remise']=15



In [37]:
clients

[{'id': 1, 'total_panier': 200, 'coupon_code': 'F20', 'remise': 20},
 {'id': 2, 'total_panier': 150, 'coupon_code': 'P30', 'remise': 45.0},
 {'id': 3, 'total_panier': 100, 'coupon_code': 'P50', 'remise': 50.0},
 {'id': 4, 'total_panier': 110, 'coupon_code': 'F15', 'remise': 15}]

In [27]:
client

{'id': 4, 'total_panier': 110, 'coupon_code': 'F15', 'remise': 15}

In [41]:
for client in clients:
    print(client['id'],client['total_panier'],client['coupon_code'],client['remise'])
    

1 200 F20 20
2 150 P30 45.0
3 100 P50 50.0
4 110 F15 15


In [42]:
#fonctions
#fonction sans argument
def bonjour():
    print("Bonjour Mr/Mme\nComment allez-vous?")
    

In [43]:
#appelation de la fonction
bonjour()

Bonjour Mr/Mme
Comment allez-vous?


In [44]:
#fonction avec un argument
def Bonjour(nom):
    print("Bonjour",nom,"\nComment allez-vous?")

In [45]:
Bonjour("Seph")

Bonjour Seph 
Comment allez-vous?


In [46]:
Bonjour(nom="Hervé")

Bonjour Hervé 
Comment allez-vous?


comment faire si on ne veut pas afficher directement le résultat d'une fonction mais plutôt assigner ce résultat à une variable?
Il faudra utiliser le mot clé return

In [47]:
#utilisation avec return
def square(a):
    return a**2
    

In [48]:
z=square(100)
#la fonction square donne le carré d'un nombre. En utilisant le mot clé return, on a pu stocker le résultat de square(100) dans la variable z

In [49]:
z

10000

In [55]:
print(liste_nom_prenom)


['Rose']


In [58]:
liste_nom_prenom


['Lima', 'Topi']

In [63]:
#fonction avec 2 arguments
liste_nom_prenom=[]
print("quel est ton nom?")
nom=input()
liste_nom_prenom.append(nom)
print("quel est ton prénom?")
prenom=input()
liste_nom_prenom.append(prenom)
def Bonjour(liste_nom_prenom):
    print("Bonjour",liste_nom_prenom,"\nComment allez-vous?")
    #appelation de la fonction
Bonjour(liste_nom_prenom)
    

quel est ton nom?


 Kol


quel est ton prénom?


 KIOL


Bonjour ['Kol', 'KIOL'] 
Comment allez-vous?


In [64]:
liste_nom_prenom


['Kol', 'KIOL']

In [65]:
#fonction à 2 arguments avec return

def somme(a,b):
    return a+b
    


In [66]:
s=somme(1000000+2,5)
s

1000007

exercice d'application
ecrivez une fonction qui a 2 arguments et qui retourne la somme de ces 2 arguments si ils sont de même type
si les arguments ne sont pas de même type, la fonction doit retourner la phrase :
"Les arguments ne sont pas de même type".


In [72]:
#correction

def SOMME(a, b):
    if type(a)==type(b):
        return a+b
    else:
        print("Les arguments ne sont pas de même type")



In [73]:
#appel de la fonction SOMME
SOMME(5,8)


13

In [74]:
somme(5,10.2)

15.2

In [75]:
somme('ariel','tot')

'arieltot'

In [77]:
SOMME(5,10.60)


Les arguments ne sont pas de même type


In [78]:
somme(5,10.2)


15.2

In [80]:
#exemple de fonctions retournant plusieurs valeurs
def soustraction_dans_les_deux_sens(a,b):
    valeur1=b-a
    valeur2=a-b
    return valeur1,valeur2

In [81]:
soustraction_dans_les_deux_sens

<function __main__.soustraction_dans_les_deux_sens(a, b)>

In [82]:
soustraction_dans_les_deux_sens()

TypeError: soustraction_dans_les_deux_sens() missing 2 required positional arguments: 'a' and 'b'

In [83]:
soustraction_dans_les_deux_sens(8,90)

(82, -82)

In [84]:
t=soustraction_dans_les_deux_sens(5,9)

In [85]:
t

(4, -4)

In [86]:
type(t)

tuple

In [87]:
c,d=t[0],t[1]

In [88]:
print(c)
print(d)

4
-4


Fonctions Lamda
les fonctions Lambda permettent d'écrire des fonctions rapidement et à la volée (en une seule ligne de code) en utilisant le mot-clé Lambda


In [89]:
#fonction somme avec mot clé def
def SOMME(a,b):
    return a+b
    

In [90]:
s=somme(2,5)
s

7

In [91]:
#fonction lambda
somme_lambda=lambda a,b:a+b

In [93]:
#appelation de fonction lambda
somme_lambda(2,5)

In [101]:
#utilisation de map() et de lambda
#la fonction lambda est souvent utilisée avec la fonction map() qui applique une fonction à tous les éléments d'un objet itérable (une liste par exemple)
diplomes=['bac','bts','licence', 'master','doctorat']
DIPLOMES=map(lambda x:x.upper(), diplomes)

In [98]:
DIPLOMES
type(DIPLOMES)

map

In [102]:
#affichage des éléments de DIPLOMES
list(DIPLOMES)

['BAC', 'BTS', 'LICENCE', 'MASTER', 'DOCTORAT']

In [103]:
nombres=[4,2,5,9,3,10]

In [104]:
nombres_carres=map(lambda x:x**2,nombres)

In [105]:
nombres_carres

In [106]:
#affichage de nombres_carres
list(nombres_carres)

[16, 4, 25, 81, 9, 100]

Fonction FILTER() associée à la fonction lambda offre un moyen de filtrer les éléments d'une liste qui ne répondent pas à certains critères

In [107]:
staff=['frodo','samwise','merry','pippin','aragorn','boromir','legolas']

In [109]:
#supprimer éléments de la liste staff dont longeur n'est pas supérieure à 6
staff_filtered=filter(lambda member:len(member)>6,staff)
type(staff_filtered)

filter

In [110]:
#la filtration est une opération très utilisée en datascience
list(staff_filtered)

['samwise', 'aragorn', 'boromir', 'legolas']

In [111]:
#Liste de compréhension
#création d'une liste avec une liste de  de compréhension
#création d'une liste avec un for
nums=[10,20,30,40,50]
new_nums=[]
for i in nums:
    new_nums.append(i+5)

new_nums
    

[15, 25, 35, 45, 55]

In [113]:
#le  code ci-dessus peut être écrit en une  seule ligne pour obtenir le meêm résultat
#avec une liste de compréhension
new_nums2=[i+5 for i in nums]
new_nums2


[15, 25, 35, 45, 55]

In [114]:
new_nums2==new_nums

True

Exercice d'application
on donne la liste : hopital=['docteur','infirmière','chercheur','medecin','chu']
Ecrire une liste de compréhension qui produit une liste composée du premier caractère de chaque élément de la liste hopital


In [116]:
hopital=['docteur','infirmière','chercheur','medecin','chu']

In [117]:
hopital2=[i[0] for i in hopital]

In [118]:
hopital2

['d', 'i', 'c', 'm', 'c']

exercice d'application
Ecrire une liste de compéhension qui produit une liste composée des valeurs au carré des éléments de range(10)


In [119]:
#correction
valeurs_au_carre=[i**2 for i in range(10)]

In [120]:
valeurs_au_carre

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [3]:
#Numpy est une librairie utilisée dans tous les projets de calcul numérique
import numpy as np

In [122]:
v=np.array([1,2,3,4])

In [123]:
v

array([1, 2, 3, 4])

tableau de dimension 1

In [124]:
type(v)

numpy.ndarray

In [4]:
#Exercice calculer imc=poids/taille**2
#liste des tailles en m
tailles=[1.83,1.85,1.64,1.90,1.72,1.89,1.59,1.68]
#liste des poids en kg
poids=[69,75,79,120,55,89,66,80]


In [5]:
#python ne sait pas faire
#imc=poids/tailles**2
#la solution est d'utiliser numpy
#création de tableaux numpy
tailles_array=np.array(tailles)
print(tailles_array)
poids_array=np.array(poids)
print(poids_array)

[1.83 1.85 1.64 1.9  1.72 1.89 1.59 1.68]
[ 69  75  79 120  55  89  66  80]


In [6]:
type(tailles_array)

numpy.ndarray

In [138]:
print(type(tailles_array))

<class 'numpy.ndarray'>


ona  créé des tableaux numpy à partir des listes poids et taille. Calculons limc


In [7]:
imc=poids_array/tailles_array**2
imc

array([20.60378035, 21.9138057 , 29.37239738, 33.24099723, 18.59113034,
       24.91531592, 26.10656224, 28.3446712 ])

In [ ]:
#Numpy sait travailler avec des tableaux comme s'ils étaient des valeurs uniques
#personnes en surpoids imc>25


In [8]:
imc>25

array([False, False,  True,  True, False, False,  True,  True])

In [9]:
imc[imc>25]


array([29.37239738, 33.24099723, 26.10656224, 28.3446712 ])

In [14]:
#création de tableaux numpy à partir d'une matrice
M=np.array([[1,3],[2,4]])
M

array([[1, 3],
       [2, 4]])

In [12]:
type(M)

numpy.ndarray

In [16]:
#accéder à un élément:1re ligne 1re colonne
M[0,0]

np.int64(1)

In [17]:
M[0,1]

np.int64(3)

In [19]:
M[1,1]

np.int64(4)

In [20]:
M[:,1]

array([3, 4])

In [21]:
M[0]

array([1, 3])

In [22]:
#toutes les lignes de la premiere colonne
M[0,:]

array([1, 3])

In [23]:
#Stocker poids et tailles dans un seul tableau numpy à 2 dimensions
family_data=np.array([tailles,poids])

In [24]:
family_data

array([[  1.83,   1.85,   1.64,   1.9 ,   1.72,   1.89,   1.59,   1.68],
       [ 69.  ,  75.  ,  79.  , 120.  ,  55.  ,  89.  ,  66.  ,  80.  ]])

family_data a deux lignes et 8 colonnes

In [25]:
#dimension
family_data.shape


(2, 8)

In [26]:
family_data.ndim

2

exercice d'application
Déterminez la taille du tableau M
Donnez la taille et le poids des 2e et 3e membre de la famille (family_data)
convertr les tailles de la liste 'tailles' en cm et nommez la nouvelle liste 'tailles_cm'

In [27]:
#correction
M.ndim

2

In [28]:
print('2e membre :',family_data[:,1])

2e membre : [ 1.85 75.  ]


In [29]:
print('3e membre :',family_data[:,2])

3e membre : [ 1.64 79.  ]


In [30]:
#création de tableau numpy à partir de la fonction range()
tab_range=np.array(range(5))

In [31]:
tab_range

array([0, 1, 2, 3, 4])

In [32]:
#avec la méthode arrange de numpy
np_arange=np.arange(5)

In [33]:
np_arange

array([0, 1, 2, 3, 4])

In [34]:
np_arange==tab_range

array([ True,  True,  True,  True,  True])

In [39]:
#donner des bornes et un pas d'increment (0.1)
np_arange2=np.arange(1.0,2.0,0.1)

In [37]:
np_arange2

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [40]:
#créer un intervalle avec un nombre précis de nombres à l'intérieur, avec ma fonction linspace: 50 éléments de 0 à 10
x=np.linspace(0.,10.,50)

In [41]:
x

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [42]:
#taille moyenne
taille_moy=np.mean(family_data[0])

In [43]:
taille_moy

np.float64(1.7625000000000002)

In [44]:
#taille médiane
taille_med=np.median(family_data[0])

In [45]:
taille_med

np.float64(1.775)

In [46]:
#ecart_type de la taille
taille_std=np.std(family_data[0])

In [47]:
taille_std

np.float64(0.1122218784373172)

In [49]:
#poids_moyen
poids_moyen=np.median(family_data[1])

In [50]:
poids_moyen

np.float64(77.0)

In [51]:
poids_med=np.median(family_data[1])

In [52]:
poids_med

np.float64(77.0)

In [53]:
#ecart_type du poids
poids_std=np.std(family_data[1])

In [54]:
poids_std

np.float64(18.17579090438708)

In [4]:
#taille et poids de 100 000 personnes: 10000 colonnes et 2 lignes
#générer les données
import numpy as np
tailles_city=np.round(np.random.normal(1.76,0.11,100000),2)
poids_city=np.round(np.random.normal(79.13,18.17,100000),2)


In [60]:
tailles_city

array([1.7 , 1.6 , 1.86, ..., 1.63, 1.7 , 1.78])

In [5]:
poids_city

array([ 62.77,  97.1 ,  64.8 , ...,  92.88, 104.64,  88.69])

In [63]:
#mettre tailles sur premiere ligne et poids en 2E ligne
np.array([tailles_city,poids_city])

array([[ 1.7 ,  1.6 ,  1.86, ...,  1.63,  1.7 ,  1.78],
       [94.22, 38.05, 90.2 , ..., 82.44, 62.3 , 90.74]])

In [64]:
#coller par collonnes
#tailles_city en premiere colonne et poids_city en 2e colonne

In [6]:
data_city=np.column_stack((tailles_city,poids_city))

In [7]:
data_city

array([[  1.79,  62.77],
       [  1.92,  97.1 ],
       [  1.86,  64.8 ],
       ...,
       [  1.86,  92.88],
       [  1.77, 104.64],
       [  1.87,  88.69]])

In [8]:
#taille moyenne data_city:toutes_lignes premiere colonne
taille_data_city_moy=np.mean(data_city[:,0])

In [9]:
taille_data_city_moy

np.float64(1.7605787000000002)

In [11]:
poids_data_city_moy=np.mean(data_city[:,1])

In [12]:
poids_data_city_moy

np.float64(79.0893084)

In [13]:
#attributs de tableau numpy array
#lattrobut shape retourne la forme d'un tableau
v=np.array([1,2,3,4])

In [14]:
v

array([1, 2, 3, 4])

In [15]:
v.shape

(4,)

In [18]:
M=np.array([[1,3],[2,4]])

In [19]:
M


array([[1, 3],
       [2, 4]])

In [20]:
M.shape


(2, 2)

In [22]:
#attribut ndim la dimension
N=np.array([[1,1],[2,6],[7,9]])

In [23]:
N.ndim

2

In [24]:
#Size=nombre elements du tableau
N.size

6

In [25]:
N

array([[1, 1],
       [2, 6],
       [7, 9]])

In [26]:
N.shape

(3, 2)

In [32]:
#remodeler le tableau en 2 lignes 3 colonnes
v2=N.reshape((2,3))

In [33]:
v2

array([[1, 1, 2],
       [6, 7, 9]])

In [34]:
#aplatir un tableau: methode RAVEL=transforme le tableau en vecteur
v2.ravel()

array([1, 1, 2, 6, 7, 9])

LIBRAIRIE PANDAS


In [35]:
#rappel numpy: enregistrer catacteristiques d'un bébé panda : pattes de 100cm, poils de 5cm en moyenne, queue de 20 cm,ventre de 
#80 cm de diametre
un_panda_numpy=np.array([100,5,20,80])

In [36]:
un_panda_numpy

array([100,   5,  20,  80])

In [37]:
#si on veut représenter plusieurs pandas on crée une liste de tableaux numpy
#famille panda
famille_panda=[
              [100,5,20,80],#maman
             [50,2.5,10,40],#bébé
             [110,6,22,80]#papa
              ]

In [38]:
famille_panda_numpy=np.array(famille_panda)

In [39]:
famille_panda_numpy

array([[100. ,   5. ,  20. ,  80. ],
       [ 50. ,   2.5,  10. ,  40. ],
       [110. ,   6. ,  22. ,  80. ]])

In [40]:
#taille des pattes de de papa panda
famille_panda_numpy[2,0]

np.float64(110.0)

In [41]:
famille_panda_numpy[:,0]

array([100.,  50., 110.])

In [43]:
#c'est bien mais pas explicite on aimerait pouvoir spécifier noms de variables (taille poils, queue, etc) d'un panda cela nus amène à utiliser librairie pandas

#importation de numpy et pandas
import numpy as np
import pandas as pd

famille_panda=[
              [100,5,20,80],#maman
             [50,2.5,10,40],#bébé
             [110,6,22,80]#papa
]
famille_panda_numpy=np.array(famille_panda)

In [45]:
print(type(famille_panda_numpy))

<class 'numpy.ndarray'>


In [47]:
#création d'une dataframe à partir d'un tableau numpy
famille_panda_df=pd.DataFrame(famille_panda)
famille_panda_df

0    1   2   3
0  100  5.0  20  80
1   50  2.5  10  40
2  110  6.0  22  80

In [67]:
#on peut faire mieux: on n'a pas noms de colonnes
famille_panda_df=pd.DataFrame(famille_panda_numpy,
                             columns=['pattes','poil','queue','ventre'],
                              index=['maman','bebe','papa']
                             
                             )

In [68]:
famille_panda_df

pattes  poil  queue  ventre
maman   100.0   5.0   20.0    80.0
bebe     50.0   2.5   10.0    40.0
papa    110.0   6.0   22.0    80.0

In [ ]:
#index dataframe= lignes

In [50]:
famille_panda_df['ventre']

maman    80.0
bebe     40.0
papa     80.0
Name: ventre, dtype: float64

In [51]:
famille_panda_df.ventre

maman    80.0
bebe     40.0
papa     80.0
Name: ventre, dtype: float64

In [52]:
#accéder aux infos de papa panda avec iloc()
famille_panda_df.iloc[2]

pattes    110.0
poil        6.0
queue      22.0
ventre     80.0
Name: papa, dtype: float64

In [53]:
#accéder aux infos de papa panda avec iloc()
famille_panda_df.loc['papa']

pattes    110.0
poil        6.0
queue      22.0
ventre     80.0
Name: papa, dtype: float64

In [54]:
#déterminons les pandas dont le diamètre du ventre est de 80cm (filtrations de données)
mask=famille_panda_df.ventre==80

In [55]:
mask

maman     True
bebe     False
papa      True
Name: ventre, dtype: bool

In [56]:
famille_panda_df[mask]

pattes  poil  queue  ventre
maman   100.0   5.0   20.0    80.0
papa    110.0   6.0   22.0    80.0

In [57]:
#pandas dont le diametre du ventre  n'est pas de 80. Il faut inverser le mask avce l'opérateur ~
famille_panda_df[~mask]

pattes  poil  queue  ventre
bebe    50.0   2.5   10.0    40.0

In [66]:
#ajout d'observations à la DataFrame pandas
quelques_pandas=pd.DataFrame(
    [
    [105,4,19,80],
    [100,5,20,80]
   ],
    columns=famille_panda_df.columns
)
quelques_pandas

pattes  poil  queue  ventre
0     105     4     19      80
1     100     5     20      80

In [72]:
tous_les_pandas=famille_panda_df._append(quelques_pandas)
tous_les_pandas


pattes  poil  queue  ventre
maman   100.0   5.0   20.0    80.0
bebe     50.0   2.5   10.0    40.0
papa    110.0   6.0   22.0    80.0
0       105.0   4.0   19.0    80.0
1       100.0   5.0   20.0    80.0

In [73]:
#dédoublonner l'index maman et 1
tous_les_pandas.drop_duplicates()

pattes  poil  queue  ventre
maman   100.0   5.0   20.0    80.0
bebe     50.0   2.5   10.0    40.0
papa    110.0   6.0   22.0    80.0
0       105.0   4.0   19.0    80.0

In [74]:
tous_les_pandas


pattes  poil  queue  ventre
maman   100.0   5.0   20.0    80.0
bebe     50.0   2.5   10.0    40.0
papa    110.0   6.0   22.0    80.0
0       105.0   4.0   19.0    80.0
1       100.0   5.0   20.0    80.0

In [78]:
pandas_uniques=tous_les_pandas.drop_duplicates()
tous_les_pandas=tous_les_pandas.drop_duplicates()
tous_les_pandas

pattes  poil  queue  ventre
maman   100.0   5.0   20.0    80.0
bebe     50.0   2.5   10.0    40.0
papa    110.0   6.0   22.0    80.0
0       105.0   4.0   19.0    80.0

In [76]:
pandas_uniques

pattes  poil  queue  ventre
maman   100.0   5.0   20.0    80.0
bebe     50.0   2.5   10.0    40.0
papa    110.0   6.0   22.0    80.0
0       105.0   4.0   19.0    80.0

In [79]:
#créer une noiuvelle colonne sexe
famille_panda_df["sexe"]=['f','f','m']

In [80]:
#accéder aux noms des colonnes
print(famille_panda_df.columns)

Index(['pattes', 'poil', 'queue', 'ventre', 'sexe'], dtype='object')


In [81]:
#obtenir nombre de lignes et colonnes de la dataframe
print(famille_panda_df.shape)

(3, 5)


In [82]:
famille_panda_df

pattes  poil  queue  ventre sexe
maman   100.0   5.0   20.0    80.0    f
bebe     50.0   2.5   10.0    40.0    f
papa    110.0   6.0   22.0    80.0    m

In [83]:
famille_panda_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, maman to papa
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   pattes  3 non-null      float64
 1   poil    3 non-null      float64
 2   queue   3 non-null      float64
 3   ventre  3 non-null      float64
 4   sexe    3 non-null      object 
dtypes: float64(4), object(1)
memory usage: 144.0+ bytes


In [84]:
#valeurs distinctes d'une colonne ventre
famille_panda_df['ventre'].unique()

array([80., 40.])

In [85]:
famille_panda_df['sexe'].unique()

array(['f', 'm'], dtype=object)

In [88]:
#lire un fichier csv avec Pandas (session de travail "tyoique" en Data Science)
#données sur les survivants de du naufrage Titanic : librairie Seaborn(créer librairies
import pandas as pd
import seaborn as sns
#chargement des données du titanic à partir de la librairie seaborn
titanic=sns.load_dataset('titanic')

In [89]:
#affichage des 5 premières lignes du dataframe
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [90]:
titanic.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

In [91]:
#les 5 dernières lignes
titanic.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [92]:
#échantillon aléatoire de la dataframe
titanic.sample(5)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
19          1       3  female   NaN      0      0   7.2250        C  Third   
878         0       3    male   NaN      0      0   7.8958        S  Third   
843         0       3    male  34.5      0      0   6.4375        C  Third   
142         1       3  female  24.0      1      0  15.8500        S  Third   
838         1       3    male  32.0      0      0  56.4958        S  Third   

       who  adult_male deck  embark_town alive  alone  
19   woman       False  NaN    Cherbourg   yes   True  
878    man        True  NaN  Southampton    no   True  
843    man        True  NaN    Cherbourg    no   True  
142  woman       False  NaN  Southampton   yes  False  
838    man        True  NaN  Southampton   yes   True

In [93]:
#modalités distinctes d'une variable
titanic['embark_town'].unique()

array(['Southampton', 'Cherbourg', 'Queenstown', nan], dtype=object)

In [94]:
#statistiques
titanic.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [96]:
#determination des colonnes avec valeurs manquantes
titanic.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [97]:
#remplacement colonnes manquantes dans colonne âge
titanic_age=titanic.fillna(value={'age':0})

In [98]:
titanic.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [99]:
titanic_age.isna().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [100]:
#remplacement par moyenne
titanic_age2=titanic.fillna(value={'age':titanic['age'].mean()})

In [101]:
titanic_age2.isna().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [102]:
#suppression lignes avec valeurs manquantes
titanic_sans_na=titanic.dropna()

In [104]:
titanic_sans_na.isna().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [107]:
#pplication méthode shape pour savoir le nombre de lignes et colonnes qui restent
titanic_sans_na.shape


(182, 15)

In [108]:
#suppression colonnes manquantes
titanic_colonnes_sans_na=titanic.drop(['age','embarked','deck','embark_town'],
                                     axis=1)

In [109]:
titanic_colonnes_sans_na

survived  pclass     sex  sibsp  parch     fare   class    who  \
0           0       3    male      1      0   7.2500   Third    man   
1           1       1  female      1      0  71.2833   First  woman   
2           1       3  female      0      0   7.9250   Third  woman   
3           1       1  female      1      0  53.1000   First  woman   
4           0       3    male      0      0   8.0500   Third    man   
..        ...     ...     ...    ...    ...      ...     ...    ...   
886         0       2    male      0      0  13.0000  Second    man   
887         1       1  female      0      0  30.0000   First  woman   
888         0       3  female      1      2  23.4500   Third  woman   
889         1       1    male      0      0  30.0000   First    man   
890         0       3    male      0      0   7.7500   Third    man   

     adult_male alive  alone  
0          True    no  False  
1         False   yes  False  
2         False   yes   True  
3         False   yes  False  
4          True    no   True  
..          ...   ...    ...  
886        True    no   True  
887       False   yes   True  
888       False    no  False  
889        True   yes   True  
890        True    no   True  

[891 rows x 11 columns]

In [110]:
titanic_colonnes_sans_na2=titanic.dropna(axis=1)

In [111]:
titanic_colonnes_sans_na2

survived  pclass     sex  sibsp  parch     fare   class    who  \
0           0       3    male      1      0   7.2500   Third    man   
1           1       1  female      1      0  71.2833   First  woman   
2           1       3  female      0      0   7.9250   Third  woman   
3           1       1  female      1      0  53.1000   First  woman   
4           0       3    male      0      0   8.0500   Third    man   
..        ...     ...     ...    ...    ...      ...     ...    ...   
886         0       2    male      0      0  13.0000  Second    man   
887         1       1  female      0      0  30.0000   First  woman   
888         0       3  female      1      2  23.4500   Third  woman   
889         1       1    male      0      0  30.0000   First    man   
890         0       3    male      0      0   7.7500   Third    man   

     adult_male alive  alone  
0          True    no  False  
1         False   yes  False  
2         False   yes   True  
3         False   yes  False  
4          True    no   True  
..          ...   ...    ...  
886        True    no   True  
887       False   yes   True  
888       False    no  False  
889        True   yes   True  
890        True    no   True  

[891 rows x 11 columns]

In [114]:
#renommer colonne
titanic.rename(columns={'sex':'sexe'},inplace=True)

In [115]:
titanic

survived  pclass    sexe   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [116]:
#supprimer lignes dont l'index est égal à 0
titanic.drop(0).head()

survived  pclass    sexe   age  sibsp  parch     fare embarked  class  \
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   
5         0       3    male   NaN      0      0   8.4583        Q  Third   

     who  adult_male deck  embark_town alive  alone  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True

In [117]:
#supprimer lcolonne age
titanic.drop(['age','sexe'],axis=1).head()

survived  pclass  sibsp  parch     fare embarked  class    who  adult_male  \
0         0       3      1      0   7.2500        S  Third    man        True   
1         1       1      1      0  71.2833        C  First  woman       False   
2         1       3      0      0   7.9250        S  Third  woman       False   
3         1       1      1      0  53.1000        S  First  woman       False   
4         0       3      0      0   8.0500        S  Third    man        True   

  deck  embark_town alive  alone  
0  NaN  Southampton    no  False  
1    C    Cherbourg   yes  False  
2  NaN  Southampton   yes   True  
3    C  Southampton   yes  False  
4  NaN  Southampton    no   True

In [120]:
#Aggrégation
#Exemple d'aggréation
titanic.groupby(['pclass','sexe'])['age'].agg(['mean','median'])

mean  median
pclass sexe                     
1      female  34.611765    35.0
       male    41.281386    40.0
2      female  28.722973    28.0
       male    30.740707    30.0
3      female  21.750000    21.5
       male    26.507589    25.0

In [121]:
#Exercice sur pandas: analyse des caractéristiques d'une voiture
#importer pandas et numpy

In [162]:
import pandas as pd
import numpy as np
#executer cette celule
file='https://raw.githubusercontent.com/JosueAfouda/TUTORIALS/main/FuelConsumptionCo2.csv'

In [163]:
#importation des données
df=pd.read_csv(file)

In [164]:
df

MODELYEAR   MAKE       MODEL    VEHICLECLASS  ENGINESIZE  CYLINDERS  \
0          2014  ACURA         ILX         COMPACT         2.0          4   
1          2014  ACURA         ILX         COMPACT         2.4          4   
2          2014  ACURA  ILX HYBRID         COMPACT         1.5          4   
3          2014  ACURA     MDX 4WD     SUV - SMALL         3.5          6   
4          2014  ACURA     RDX AWD     SUV - SMALL         3.5          6   
...         ...    ...         ...             ...         ...        ...   
1062       2014  VOLVO    XC60 AWD     SUV - SMALL         3.0          6   
1063       2014  VOLVO    XC60 AWD     SUV - SMALL         3.2          6   
1064       2014  VOLVO    XC70 AWD     SUV - SMALL         3.0          6   
1065       2014  VOLVO    XC70 AWD     SUV - SMALL         3.2          6   
1066       2014  VOLVO    XC90 AWD  SUV - STANDARD         3.2          6   

     TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
0             AS5        Z                   9.9                  6.7   
1              M6        Z                  11.2                  7.7   
2             AV7        Z                   6.0                  5.8   
3             AS6        Z                  12.7                  9.1   
4             AS6        Z                  12.1                  8.7   
...           ...      ...                   ...                  ...   
1062          AS6        X                  13.4                  9.8   
1063          AS6        X                  13.2                  9.5   
1064          AS6        X                  13.4                  9.8   
1065          AS6        X                  12.9                  9.3   
1066          AS6        X                  14.9                 10.2   

      FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS  
0                      8.5                        33           196  
1                      9.6                        29           221  
2                      5.9                        48           136  
3                     11.1                        25           255  
4                     10.6                        27           244  
...                    ...                       ...           ...  
1062                  11.8                        24           271  
1063                  11.5                        25           264  
1064                  11.8                        24           271  
1065                  11.3                        25           260  
1066                  12.8                        22           294  

[1067 rows x 13 columns]

In [165]:
#afficher les 5 premieres lignes de df
df.head()

MODELYEAR   MAKE       MODEL VEHICLECLASS  ENGINESIZE  CYLINDERS  \
0       2014  ACURA         ILX      COMPACT         2.0          4   
1       2014  ACURA         ILX      COMPACT         2.4          4   
2       2014  ACURA  ILX HYBRID      COMPACT         1.5          4   
3       2014  ACURA     MDX 4WD  SUV - SMALL         3.5          6   
4       2014  ACURA     RDX AWD  SUV - SMALL         3.5          6   

  TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
0          AS5        Z                   9.9                  6.7   
1           M6        Z                  11.2                  7.7   
2          AV7        Z                   6.0                  5.8   
3          AS6        Z                  12.7                  9.1   
4          AS6        Z                  12.1                  8.7   

   FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS  
0                   8.5                        33           196  
1                   9.6                        29           221  
2                   5.9                        48           136  
3                  11.1                        25           255  
4                  10.6                        27           244

In [166]:
#afficher les 5 dernières lignes
df.tail()


MODELYEAR   MAKE     MODEL    VEHICLECLASS  ENGINESIZE  CYLINDERS  \
1062       2014  VOLVO  XC60 AWD     SUV - SMALL         3.0          6   
1063       2014  VOLVO  XC60 AWD     SUV - SMALL         3.2          6   
1064       2014  VOLVO  XC70 AWD     SUV - SMALL         3.0          6   
1065       2014  VOLVO  XC70 AWD     SUV - SMALL         3.2          6   
1066       2014  VOLVO  XC90 AWD  SUV - STANDARD         3.2          6   

     TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
1062          AS6        X                  13.4                  9.8   
1063          AS6        X                  13.2                  9.5   
1064          AS6        X                  13.4                  9.8   
1065          AS6        X                  12.9                  9.3   
1066          AS6        X                  14.9                 10.2   

      FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS  
1062                  11.8                        24           271  
1063                  11.5                        25           264  
1064                  11.8                        24           271  
1065                  11.3                        25           260  
1066                  12.8                        22           294

In [168]:
#Afficher les infos sur df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067 entries, 0 to 1066
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   MODELYEAR                 1067 non-null   int64  
 1   MAKE                      1067 non-null   object 
 2   MODEL                     1067 non-null   object 
 3   VEHICLECLASS              1067 non-null   object 
 4   ENGINESIZE                1067 non-null   float64
 5   CYLINDERS                 1067 non-null   int64  
 6   TRANSMISSION              1067 non-null   object 
 7   FUELTYPE                  1067 non-null   object 
 8   FUELCONSUMPTION_CITY      1067 non-null   float64
 9   FUELCONSUMPTION_HWY       1067 non-null   float64
 10  FUELCONSUMPTION_COMB      1067 non-null   float64
 11  FUELCONSUMPTION_COMB_MPG  1067 non-null   int64  
 12  CO2EMISSIONS              1067 non-null   int64  
dtypes: float64(4), int64(4), object(5)
memory usage: 108.5+ KB


In [169]:
#faites un résumé statistique des données n'incluant que
#les variables quantitatives
df.describe()


MODELYEAR   ENGINESIZE    CYLINDERS  FUELCONSUMPTION_CITY  \
count     1067.0  1067.000000  1067.000000           1067.000000   
mean      2014.0     3.346298     5.794752             13.296532   
std          0.0     1.415895     1.797447              4.101253   
min       2014.0     1.000000     3.000000              4.600000   
25%       2014.0     2.000000     4.000000             10.250000   
50%       2014.0     3.400000     6.000000             12.600000   
75%       2014.0     4.300000     8.000000             15.550000   
max       2014.0     8.400000    12.000000             30.200000   

       FUELCONSUMPTION_HWY  FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  \
count          1067.000000           1067.000000               1067.000000   
mean              9.474602             11.580881                 26.441425   
std               2.794510              3.485595                  7.468702   
min               4.900000              4.700000                 11.000000   
25%               7.500000              9.000000                 21.000000   
50%               8.800000             10.900000                 26.000000   
75%              10.850000             13.350000                 31.000000   
max              20.500000             25.800000                 60.000000   

       CO2EMISSIONS  
count   1067.000000  
mean     256.228679  
std       63.372304  
min      108.000000  
25%      207.000000  
50%      251.000000  
75%      294.000000  
max      488.000000

In [172]:
#déterminez les valeurs distinctes de chaque variable qualitative de df
variables_qualitatives=df.select_dtypes(include='object').columns

In [175]:
variables_qualitatives

Index(['MAKE', 'MODEL', 'VEHICLECLASS', 'TRANSMISSION', 'FUELTYPE'], dtype='object')

In [176]:
for i in variables_qualitatives:
    print("Colonne",i,":", df[i].unique())
    print('-'*150)

Colonne MAKE : ['ACURA' 'ASTON MARTIN' 'AUDI' 'BENTLEY' 'BMW' 'BUICK' 'CADILLAC'
 'CHEVROLET' 'CHRYSLER' 'DODGE' 'FIAT' 'FORD' 'GMC' 'HONDA' 'HYUNDAI'
 'INFINITI' 'JAGUAR' 'JEEP' 'KIA' 'LAMBORGHINI' 'LAND ROVER' 'LEXUS'
 'LINCOLN' 'MASERATI' 'MAZDA' 'MERCEDES-BENZ' 'MINI' 'MITSUBISHI' 'NISSAN'
 'PORSCHE' 'RAM' 'ROLLS-ROYCE' 'SCION' 'SMART' 'SRT' 'SUBARU' 'TOYOTA'
 'VOLKSWAGEN' 'VOLVO']
------------------------------------------------------------------------------------------------------------------------------------------------------
Colonne MODEL : ['ILX' 'ILX HYBRID' 'MDX 4WD' 'RDX AWD' 'RLX' 'TL' 'TL AWD' 'TSX' 'DB9'
 'RAPIDE' 'V8 VANTAGE' 'V8 VANTAGE S' 'VANQUISH' 'A4' 'A4 QUATTRO'
 'A5 CABRIOLET QUATTRO' 'A5 QUATTRO' 'A6 QUATTRO'
 'A6 QUATTRO TDI CLEAN DIESEL' 'A7 QUATTRO' 'A7 QUATTRO TDI CLEAN DIESEL'
 'A8' 'A8 TDI CLEAN DIESEL' 'A8L' 'A8L TDI CLEAN DIESEL' 'ALLROAD QUATTRO'
 'Q5' 'Q5 HYBRID' 'Q5 TDI CLEAN DIESEL' 'Q7' 'Q7 TDI CLEAN DIESEL' 'R8'
 'R8 SPYDER' 'RS5' 'RS5 CABRIOLET'